### ISSUE TITLE
Chests break after floor cleared

### ISSUE THREAD

**Issue by akarle** [mbkarle/firstgames#18]
Im pretty sure the issue has to do with the `print` function and how it goes back 2 messages...

#4 

Sir..

**Comment by akarle** [comment]
Ok so I found the problem... 

In `combat_helper` it sets this `window.onclick` where EVERY time you click it will dtect if the enemy on the list you are currently on is dead and if so it `print`s "you defeated the enemy!" followed by "the fog clears..."

You can verify this yourself @mbkarle  by clicking on the map after the floor is cleared and then printing `messageArray`. The thing grows by 2 per click.

Soooooo, first way I got around this was by only checking this dead enemy if the floor wasn't cleared. PROBLEM: entering a custom combat breaks because it will never detect custom enemy is dead. 

So I tried  adding the clause `if(!floorCleared || custom_combat)` but NOW the problem is that yes you can detect a CC win, BUT, now the messageArray is thrown all off again and this problem rearises...

Sigh.#4 #4 #4 pleasssse.

Can we consider not using a messageArray @mbkarle ?

I believe this is also the source of your error you had on the content-branch

**Comment by mbkarle** [comment]
I believe I have solved the problem at hand here on content-branch. The issue does not appear to lie in the `messageArray` but rather in the `window.onclick` listener. My solution has been to turn off this listener after the enemy has died, so that future clicks will not trigger its functions. 

I do not think the `messageArray` is causing any of the issues here because while it does serve to show the _symptoms_ of the issues (growing 2 per click due to `window.onclick`) it is not actually _responsible_ for any of them. The only time when the array is currently influencing the code is when `lastMessage` param is passed, which only occurs at chests and during descend. Therefore I do not believe that `messageArray` should be removed.

Upon merge with content-branch I believe that this issue may be closed.

**Comment by akarle** [comment]
confirmed fixed by commit 51...
